=== camiloahm/jdhtuq/communication/socket-communication/src/main/resources/schema/communication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.DHT-UQ.org/communication" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.DHT-UQ.org/communication">   

    <xsd:element name="communication">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="instance" minOccurs="1"
    				maxOccurs="1">
    			</xsd:element>
    			<xsd:element ref="time" minOccurs="1" maxOccurs="1"></xsd:element>
    			<xsd:element ref="params" maxOccurs="1" minOccurs="1"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>

    <xsd:element name="time">
    	<xsd:complexType>
    		<xsd:attribute name="waitingResult" default="2000">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:long">
    					<xsd:minInclusive value="100"></xsd:minInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:attribute>
    	</xsd:complexType>
    </xsd:element>

    <xsd:element name="instance">
    	<xsd:complexType>
    		<xsd:attribute name="class" use="required">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:minLength value="1"></xsd:minLength>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:attribute>
    	</xsd:complexType>
    </xsd:element>

    <xsd:element name="params">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>

    <xsd:element name="param">
    	<xsd:complexType>
    		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	</xsd:complexType>
    </xsd:element>
</xsd:schema>

=== camiloahm/jdhtuq/p2p/chord/src/main/resources/chord_properties/communication.xml
<?xml version="1.0" encoding="UTF-8"?>
<communication xmlns="http://www.DHT-UQ.org/communication"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.DHT-UQ.org/communication communication.xsd ">
	<instance
		class="co.edu.uniquindio.utils.communication.transfer.structure.CommunicationManagerStructure" />


	<!--	<instance-->
	<!--
		class="co.edu.uniquindio.utils.communication.transfer.network.CommunicationManagerUDP"
		/>
	-->

	<time waitingResult="2000" />
	<params>
		<param name="BUFFER_SIZE_MULTICAST">1024</param>
		<param name="IP_MULTICAST">224.0.0.2</param>
		<param name="PORT_MULTICAST">2000</param>
		<param name="PORT_TCP_RESOURCE">2001</param>
		<param name="PORT_TCP">2002</param>
		<param name="PORT_UDP">2003</param>
		<param name="BUFFER_SIZE_UDP">1024</param>
	</params>
</communication>
